services:
  planka:
    image: ghcr.io/plankanban/planka:2.0.0-rc.2
    restart: on-failure
    volumes:
      - favicons:/app/public/favicons
      - user-avatars:/app/public/user-avatars
      - background-images:/app/public/background-images
      - attachments:/app/private/attachments
    networks:
      - proxy
      - backend
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.${PLANKA_UID}.loadbalancer.server.port=1337"
        # HTTP
        - "traefik.http.routers.${PLANKA_UID}-http.entrypoints=web"
        - "traefik.http.routers.${PLANKA_UID}-http.rule=Host(`${PLANKA_HOSTNAME}`)"
        - "traefik.http.routers.${PLANKA_UID}-http.service=${PLANKA_UID}"
        - "traefik.http.routers.${PLANKA_UID}-http.middlewares=auto-https@docker"
        # HTTPS
        - "traefik.http.routers.${PLANKA_UID}-https.entrypoints=websecure"
        - "traefik.http.routers.${PLANKA_UID}-https.rule=Host(`${PLANKA_HOSTNAME}`)"
        - "traefik.http.routers.${PLANKA_UID}-https.service=${PLANKA_UID}"
        - "traefik.http.routers.${PLANKA_UID}-https.tls=true"
        - "traefik.http.routers.${PLANKA_UID}-https.tls.certresolver=lehttpresolver"
        - "traefik.http.middlewares.auto-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.auto-https.redirectscheme.permanent=true"
    secrets:
      - mysql_root_password
      - planka_secret
      - planka_password
    environment:
      - BASE_URL=https://${PLANKA_HOSTNAME}
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - DATABASE_PASSWORD__FILE=/run/secrets/mysql_root_password
      - SECRET_KEY__FILE=/run/secrets/planka_secret
      - DEFAULT_ADMIN_EMAIL="${DEFAULT_ADMIN_EMAIL:-demo@demo.demo}"
      - DEFAULT_ADMIN_USERNAME="${DEFAULT_ADMIN_USERNAME:-admin}"
      - DEFAULT_ADMIN_PASSWORD="${DEFAULT_ADMIN_PASSWORD:-demo}"
      - DEFAULT_ADMIN_NAME="${DEFAULT_ADMIN_NAME:-admin}"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/mysql_root_password
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    secrets:
      - mysql_root_password

volumes:
  favicons:
  user-avatars:
  background-images:
  attachments:
  db-data:

networks:
  backend:
  proxy:
    external: true

secrets:
  mysql_root_password:
    external: true
  planka_password:
    external: true
  planka_secret:
    external: true
