version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - backend

  wordpress:
    image: kylefs/dev-wp:latest
    volumes:
      - "wp_data:/var/www/html"
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "80"
      - "9000"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${TRAEFIK_UID}.entrypoints=web"
        - "traefik.http.routers.${TRAEFIK_UID}.rule=Host(`${TRAEFIK_HOSTNAME}`)"
        - "traefik.http.routers.${TRAEFIK_UID}-secure.rule=Host(`${TRAEFIK_HOSTNAME}`)"
        - "traefik.http.routers.${TRAEFIK_UID}-secure.tls.certresolver=lehttpresolver"
        - "traefik.http.routers.${TRAEFIK_UID}-secure.entrypoints=websecure"
        - "traefik.http.services.${TRAEFIK_UID}.loadbalancer.server.port=80"
        - "traefik.tcp.routers.${TRAEFIK_UID}-xdebug.rule=Host(`${TRAEFIK_HOSTNAME}`)"
        - "traefik.tcp.routers.${TRAEFIK_UID}-xdebug.entrypoints=xdebug"
        - "traefik.tcp.routers.${TRAEFIK_UID}-xdebug.service=${TRAEFIK_UID}-xdebug-svc"
        - "traefik.tcp.services.${TRAEFIK_UID}-xdebug-svc.loadbalancer.server.port=9000"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define( 'BACKUPBUDDY_API_ENABLE', true );
    networks:
      - proxy
      - backend

volumes:
  db_data:
  wp_data:

networks:
  backend:
  proxy:
    external: true