version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - back

  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    restart: unless-stopped
    ports:
      - "80"
    labels:
      - "traefik.http.routers.${TRAEFIK_UID}.rule=Host(`${TRAEFIK_HOSTNAME}`)"
      - "traefik.http.routers.${TRAEFIK_UID}.tls.certresolver=lehttpresolver"
      - "traefik.http.routers.${TRAEFIK_UID}.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_UID}.middlewares=httpredirectscheme"
      - "traefik.http.services.${TRAEFIK_UID}.loadbalancer.server.port=80"
      - "traefik.http.middlewares.httpredirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.httpredirectscheme.redirectscheme.permanent=true"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - front
      - back

volumes:
  db_data:
  wp_data:

networks:
  front:
    external:
      name: front
  back: