version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - "db_data:/var/lib/mysql"
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${DEV_STACK_USER}
      MYSQL_PASSWORD: ${DEV_STACK_PASS}
    networks:
      - backend

  wordpress:
    image: kylefs/dev-wp:latest
    volumes:
      - "wp_data:/var/www/html"
    restart: "no"
    depends_on:
      - db
    ports:
      - "9001"
    networks:
      - proxy
      - backend
      - frontend

  cli:
    image: wordpress:cli
    restart: "no"
    user: "33:33"
    volumes:
      - "wp_data:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DEV_STACK_USER}
      WORDPRESS_DB_PASSWORD: ${DEV_STACK_PASS}
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'BACKUPBUDDY_API_ENABLE', true );
    command: >
      /bin/sh -c '
      wp core download;
      sleep 20;
      wp core install --path="/var/www/html" --url="https://miles.dev.kylespiller.com" --title="Local Wordpress By Docker" --admin_user=admin --admin_password=secret --admin_email=foo@bar.com
      '
    depends_on:
      - db
      - wordpress
    networks:
      - backend

  apache:
    image: kylefs/dev-apache:latest
    volumes:
      - "wp_data:/var/www/html"
      - "pma_data:/var/www/pma"
    depends_on:
      - db
      - wordpress
      - pma
    ports:
      - "8080"
    restart: "no"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${DEV_UID}.entrypoints=web"
        - "traefik.http.routers.${DEV_UID}.rule=Host(`${DEV_WAN_HOSTNAME}`)"
        - "traefik.http.routers.${DEV_UID}-secure.rule=Host(`${DEV_WAN_HOSTNAME}`)"
        - "traefik.http.routers.${DEV_UID}-secure.tls.certresolver=lehttpresolver"
        - "traefik.http.routers.${DEV_UID}-secure.entrypoints=websecure"
        - "traefik.http.services.${DEV_UID}.loadbalancer.server.port=80"
        - "traefik.http.middlewares.auto-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.auto-https.redirectscheme.permanent=true"
        - "traefik.http.routers.${DEV_UID}.middlewares=auto-https@docker"
    networks:
      - proxy
      - frontend

  sftp:
    image: atmoz/sftp
    restart: "no"
    volumes:
      - "wp_data:/home/${DEV_STACK_USER}/html"
    ports:
      - "22"
    command: ${DEV_STACK_USER}:${DEV_STACK_PASS}:33:33

  pma:
    image: phpmyadmin/phpmyadmin:fpm
    restart: "no"
    volumes:
      - "/sessions"
      - "pma_data:/var/www/html"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    networks:
      - backend
      - frontend

volumes:
  db_data:
  wp_data:
  pma_data:

networks:
  backend:
  frontend:
  proxy:
    external: true