version: '3.8'

services:
  db:
    image: kylefs/dev-mysql:latest
    volumes:
      - "db_data:/var/lib/mysql"
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER_FILE: /run/secrets/wordpress_user
      MYSQL_PASSWORD_FILE: /run/secrets/wordpress_password
    networks:
      - backend
    secrets:
      - mysql_root_password
      - wordpress_user
      - wordpress_password
    healthcheck:
      test: [ "CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  wordpress:
    image: kylefs/dev-wp:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER_FILE: /run/secrets/wordpress_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_password
      WORDPRESS_TABLE_PREFIX: "wp_"
      DEV_XDEBUG_MODE: "${DEV_XDEBUG_MODE:-none}"
    ports:
      - "9003"
    volumes:
      - "wp_data:/var/www/html"
      - "xdebug_data:/var/www/xdebug"
      - "log_data:/var/www/log"
      - "shared_data:/var/www/shared"
    restart: "no"
    depends_on:
      - db
    networks:
      - backend
      - frontend
    secrets:
      - wordpress_user
      - wordpress_password
    healthcheck:
      test: [ "CMD", 'php', '-v' ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  apache:
    image: kylefs/dev-apache:latest
    volumes:
      - "wp_data:/var/www/html"
      - "pma_data:/var/www/pma"
      - "log_data:/var/www/log"
    depends_on:
      - db
      - wordpress
      - pma
    ports:
      - "8080"
      - "80"
    restart: "no"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.${DEV_UID}.loadbalancer.server.port=80"
        - "traefik.http.routers.${DEV_UID}.entrypoints=web,websecure"
        - "traefik.http.routers.${DEV_UID}.rule=Host(`${DEV_UID}.${DEV_DOMAIN}`)"
        - "traefik.http.routers.${DEV_UID}.service=${DEV_UID}"
        - "traefik.http.routers.${DEV_UID}.middlewares=auto-https@docker"
        - "traefik.http.routers.${DEV_UID}.tls=true"
        - "traefik.http.routers.${DEV_UID}.tls.certresolver=lehttpresolver"
        - "traefik.http.middlewares.auto-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.auto-https.redirectscheme.permanent=true"
    networks:
      - proxy
      - frontend

  sftp:
    image: atmoz/sftp
    restart: "no"
    volumes:
      - "sftp_user_data:/etc/sftp"
      - "wp_data:/home/wordpress/html"
      - "xdebug_data:/home/wordpress/xdebug"
      - "log_data:/home/wordpress/log"
      - "shared_data:/home/wordpress/shared"
    ports:
      - "22"

  pma:
    image: phpmyadmin/phpmyadmin:5.1.3-fpm
    restart: "no"
    volumes:
      - "pma_data:/var/www/html"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1024M
    networks:
      - backend
      - frontend

volumes:
  db_data:
  wp_data:
  xdebug_data:
  pma_data:
  log_data:
    driver: local
    driver_opts:
        type: 'none'
        o: 'bind'
        device: '/var/log/docker-dev'
  shared_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/docker-dev/shared'
  sftp_user_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/docker-dev/conf/sftp'

networks:
  backend:
  frontend:
  proxy:
    external: true

secrets:
  mysql_root_password:
    external: true
  wordpress_user:
    external: true
  wordpress_password:
    external: true
