version: '3.3'

services:
  db:
    image: kylefs/dev-mysql:latest
    volumes:
      - "db_data:/var/lib/mysql"
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${DEV_STACK_USER}
      MYSQL_PASSWORD: ${DEV_STACK_PASS}
    networks:
      - backend
    secrets:
      - db_root_password

  wordpress:
    image: kylefs/dev-wp:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DEV_STACK_USER}
      WORDPRESS_DB_PASSWORD: ${DEV_STACK_PASS}
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'BACKUPBUDDY_API_ENABLE', true );
        define( 'FORCE_SSL_ADMIN', true );
    ports:
      - "9003"
    volumes:
      - "wp_data:/var/www/html"
      - "xdebug_data:/var/www/xdebug"
      - "log_data:/var/www/log"
      - "shared_data:/var/www/shared"
    restart: "no"
    depends_on:
      - db
    networks:
      - backend
      - frontend
    command:
      ["${DEV_XDEBUG_MODE:-none}", "${DEV_XDEBUG_IP}"]

  apache:
    image: kylefs/dev-apache:latest
    volumes:
      - "wp_data:/var/www/html"
      - "pma_data:/var/www/pma"
      - "log_data:/var/www/log"
    depends_on:
      - db
      - wordpress
      - pma
    ports:
      - "8080"
      - "80"
    restart: "no"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.${DEV_UID}.loadbalancer.server.port=80"
        # HTTP
        - "traefik.http.routers.${DEV_UID}-http.entrypoints=web"
        - "traefik.http.routers.${DEV_UID}-http.rule=Host(`${DEV_WAN_HOSTNAME}`)"
        - "traefik.http.routers.${DEV_UID}-http.service=${DEV_UID}"
        - "traefik.http.routers.${DEV_UID}-http.middlewares=auto-https@docker"
        # HTTPS
        - "traefik.http.routers.${DEV_UID}-https.entrypoints=websecure"
        - "traefik.http.routers.${DEV_UID}-https.rule=Host(`${DEV_WAN_HOSTNAME}`)"
        - "traefik.http.routers.${DEV_UID}-https.service=${DEV_UID}"
        - "traefik.http.routers.${DEV_UID}-https.tls=true"
        - "traefik.http.routers.${DEV_UID}-https.tls.certresolver=lehttpresolver"
        - "traefik.http.middlewares.auto-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.auto-https.redirectscheme.permanent=true"
    networks:
      - proxy
      - frontend

  sftp:
    image: atmoz/sftp
    restart: "no"
    volumes:
      - "wp_data:/home/${DEV_STACK_USER}/html"
      - "xdebug_data:/home/${DEV_STACK_USER}/xdebug"
      - "log_data:/home/${DEV_STACK_USER}/log"
      - "shared_data:/home/${DEV_STACK_USER}/shared"
    ports:
      - "22"
    command: ${DEV_STACK_USER}:${DEV_STACK_PASS}:33:33

  pma:
    image: phpmyadmin/phpmyadmin:fpm
    restart: "no"
    volumes:
      - "/sessions"
      - "pma_data:/var/www/html"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    networks:
      - backend
      - frontend

volumes:
  db_data:
  wp_data:
  xdebug_data:
  pma_data:
  log_data:
    driver: local
    driver_opts:
        type: 'none'
        o: 'bind'
        device: '/var/log/docker-dev'
  shared_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/docker-dev/shared'

networks:
  backend:
  frontend:
  proxy:
    external: true

secrets:
  mysql_root_password:
    file: /opt/docker-dev/secrets/mysql_root_password.txt
